name: Deploy To Staging

on:
  issue_comment:
    types: [ created ]

jobs:
  create_feature_branch:
    runs-on: ubuntu-latest
    if: ${{ github.event.comment.body == 'CB-F'}}
    steps:
      - name: Create Feature Branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'feature/${{ github.event.issue.number}}-${{issue.title.issue.number}}'
  create_bug_branch:
    runs-on: ubuntu-latest
    if: ${{ github.event.comment.body == 'CB-B'}}
    steps:
      - name: Create Bug Branch
        uses: robvanderleek/create-issue-branch@v1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  create_hotfix_branch:
    runs-on: ubuntu-latest
    if: ${{ github.event.comment.body == 'CB-H'}}
    steps:
      - name: Create Hotfix Branch
        uses: robvanderleek/create-issue-branch@v1.5
        with:
          branchName: 'hotfix/${{ github.event.issue.number}}-${{issue.title.issue.number}}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  create-issue-branch:
    name: "create issue branch"
    runs-on: ubuntu-latest
    steps:
      - name: create the issue branch
        uses: robvanderleek/create-issue-branch@v1.5
        id: create-issue-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
