name: Deploy To Staging

on:
#   pull_request:
    
#   issue_comment:
#     types: [ created ]
  issues:
    types:
      - opened
      - reopened
      - closed

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      
      - name: Discord notification
        uses: Ilshidur/action-discord@0.3.2
        env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
            DISCORD_EMBEDS: '[{"color":16750848,"title":"Issue #${{github.event.issue.number}} - ${{ github.event.action }}","url":"${{ github.event.issue.html_url }}","author":{"name":"${{ github.event.issue.user.login }}","icon_url":"${{ github.event.issue.user.avatar_url }}"},"description":"${{ github.event.issue.title}}"}]'
        
#       - run: echo "$GITHUB_HEAD_REF"
#       - run: echo "$GITHUB_BASE_REF"
      
#   create_feature_branch:
#     runs-on: ubuntu-latest
#     if: ${{ github.event.comment.body == 'CB-F'}}
#     steps:
#       - name: Create Feature Branch
#         uses: peterjgrainger/action-create-branch@v2.0.1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           branch: feature/${{github.event.issue.number}}
