name: Deploy To Staging

on:
  issue_comment:
    types: [ created ]

jobs:
  create_feature_branch:
    runs-on: ubuntu-latest
    if: ${{ github.event.comment.body == 'CB-F'}}
    steps:
      - name: Create Feature Branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{github.event.issue.number}}
