
name: Post On Discord

on:
  workflow_dispatch:
  push:
    branches:
      - release/*

jobs:
  post-message:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: hmarr/debug-action@v2
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed. @{{ EVENT_PAYLOAD.head_commit.username }}\{{ EVENT_PAYLOAD.head_commit.name }} - {{GITHUB_REPOSITORY}}@{{EVENT_PAYLOAD.head_commit.id}}'
