
name: Post On Discord

on:
  workflow_dispatch:
#pritier
#linter

jobs:
  post-message:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[{"color":39423,"title":"Some title","url":"https://discord.js.org","author":{"name":"Some name","icon_url":"https://i.im gur.com/AfFp7pu.png","url":"https://discord.js.org"},"description":"Some description here","thumbnail":{"url":"https://i .imgur.com/AfFp7pu.png"},"fields":[{"name":"Regular field title","value":"Some value here"},{"name":"​","value":"​","inl ine":false},{"name":"Inline field title","value":"Some value here","inline":true},{"name":"Inline field title","value":" Some value here","inline":true},{"name":"Inline field title","value":"Some value here","inline":true}],"image":{"url":"h ttps://i.imgur.com/AfFp7pu.png"},"timestamp":"2021-11-23T18:31:56.754Z","footer":{"text":"Some footer text here","icon_u rl":"https://i.imgur.com/AfFp7pu.png"}}]'
          
          
          #'[{"title":"Meow!","color":1127128},{"title":"Meow-meow!","color":14177041}]'
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
